config/routes.rb
Rails.application.routes.draw do
  root 'reservations#index'
  resources :reservations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :name, :time, :email, :party_size, :date, presence: true
  validates :name, length: {maximum: 20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    render 'index'
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to @reservation
    else
      render 'new'
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
    render 'show'
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.udpate(params[:reservation]).permit(:name, :email, :party_size, :date, :time)
      redirect_to @reservation
    else
      render 'edit'
    end
  end

  private
    def reservation_params
      params.require(:reservation).permit(:name, :email, :party_size, :date, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guacamole Hut</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Barrio" rel="stylesheet">
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/reservations/edit.html.erb
<section>
  <h1>Reservations</h1>
  <% if @reservation.errors.any? %>
  <ul class="errors">
    <% @reservation.errors.full_messages.each do |error| %>
    <li>
      <%= error %>
    </li>
    <% end %><!-- end errors li -->
  </ul>
  <% end %><!-- end errors each -->
  <%= form_for :reservation, url: reservations_path(@reservaton) do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :party_size %>
    <%= f.text_field :party_size %>
  </p>
  <p>
    <%= f.label :date %>
    <%= f.date_field :date %>
  </p>
  <p>
    <%= f.label :time %>
    <%= f.time_select :time %>
  </p>
  <p>
    <%= f.submit "Book", class: 'button' %>
  </p>
  <% end %>
</section>

app/views/reservations/index.html.erb
<section>
  <h1>Hallo!</h1>
  <nav class="main-nav">
    <%= link_to 'new reservation', new_reservation_path(@reservation) %>
    
  </nav>

</section>

app/views/reservations/new.html.erb
<section>
  <h1>Reservations</h1>
  <% if @reservation.errors.any? %>
  <ul class="errors">
    <% @reservation.errors.full_messages.each do |error| %>
    <li>
      <%= error %>
    </li>
    <% end %><!-- end errors li -->
  </ul>
  <% end %><!-- end errors each -->
  <%= form_for :reservation, url: reservations_path(@reservaton) do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :party_size %>
    <%= f.text_field :party_size %>
  </p>
  <p>
    <%= f.label :date %>
    <%= f.date_field :date %>
  </p>
  <p>
    <%= f.label :time %>
    <%= f.time_select :time %>
  </p>
  <p>
    <%= f.submit "Book", class: 'button' %>
  </p>
  <% end %>
</section>

app/views/reservations/show.html.erb
<section>
  <h1>yay</h1>
  <h2>Thank you for booking <%= @reservation.name  %>!</h2>
  <p>
    Your reservation is for
    <%= @reservation.time.to_s(:time) %>pm
    <%= @reservation.date.strftime("%m/%d") %> for
    <%= @reservation.party_size %> people!
  </p>
  <p>
    A confirmation will be sent to
    <%= @reservation.email %>
  </p>
  <p>
    If you need to make changes or delete your reservation select <%= link_to 'change reservations', edit_reservation_path(@reservation) %>
  </p>
</section>